### ISSUE TITLE
bug in meta data when writing fits files with UnBinnedData class

### ISSUE THREAD

**Issue by ckarwin** [cositools/cosipy#101]
When writing the un-binned data to a fits file, the meta data includes the keyword "data_file". There are two problems with this.
1. If the name of the file is too long, this will cause an error (as found by @eneights). This can happen because the code is using the data file name in the inputs yaml file, which often contains a long path. 
2. This meta data doesn't apply when combining multiple fits files.

**Comment by israelmcmc** [comment]
@ckarwin Can this be closed?

**Comment by ckarwin** [comment]
@israelmcmc Not yet. It will be an easy fix. I'll get to it soon.
