### ISSUE TITLE
A KeyError when running SpectralFit.ipynb in tutorials

### ISSUE THREAD

**Issue by KeigoOkuma** [cositools/cosipy#102]
When running SpectralFit.ipynb in tutorials, I got `KeyError: "Parameter 'ori_file' doesn't exists"` at `grb = BinnedData(data_path / "grb.yaml")`.
I checked contents of grb.yaml and the parameter 'ori_file' doesn't exists in the file.

**Comment by ckarwin** [comment]
Thanks @KeigoOkuma! Can you just add the ori_file keyword to your yaml file for now? @eneights will make a PR to fix this later today.

**Comment by KeigoOkuma** [comment]
OK, Thanks!

**Comment by ckarwin** [comment]
This issue has been fixed with PR #103.
