### ISSUE TITLE
Lots of warning when running parallel_ts_fit

### ISSUE THREAD

**Issue by ckierans** [cositools/cosipy#117]
I'm getting >10 warnings duplicated by the number of cores when running parallel_ts_fit. Most are related to 3ML and astromodels, but I'm not sure why they're showing up here when calling this function.

<img width="910" alt="Screenshot 2023-12-01 at 12 40 43 PM" src="https://github.com/cositools/cosipy/assets/33991471/22b63a69-aa43-4100-a41c-9466e6c553e3">

**Comment by Yong2Sheng** [comment]
Hi @ckierans, this warnings are silenced in #113. Could you please take a look when you are free? Thanks!

**Comment by israelmcmc** [comment]
I believe this was fixed in DC2. Reopen if needed.
