### ISSUE TITLE
Install astromodels and threeml packages

### ISSUE THREAD

**Issue by PbU-Jason** [cositools/cosipy#12]
Using Mac M1 to run `pip install astromodels` and `pip install threeml` in python 3.9 environment may encounter **_error: subprocess-exited-with-error_**

The solution is listed below:

1. `pip install cython`
2. `xcode-select --install`
3. `brew install hdf5`
4. `brew install c-blosc`
5. `export HDF5_DIR=/opt/homebrew/opt/hdf5`
6. `export BLOSC_DIR=/opt/homebrew/opt/c-blosc`
7. `pip install astromodels`
8. `pip install threeml`

Reference:

1. https://stackoverflow.com/questions/73029883/could-not-find-hdf5-installation-for-pytables-on-m1-mac
2. https://github.com/freqtrade/freqtrade/issues/4162

**Comment by israelmcmc** [comment]
Thanks, @PbU-Jason. I'll keep this open until we get ready for release.

**Comment by israelmcmc** [comment]
Done in DC2
