### ISSUE TITLE
Can't download Response file

### ISSUE THREAD

**Issue by parshadkp** [cositools/cosipy#130]
Downloading "cosi-pipeline-public/COSI-SMEX/DC2/ResponsesSMEXv12.Continuum.HEALPixO3_10bins_log_flat.binnedimaging.imagingresponse.nonsparse_nside8.area.good_chunks_unzip.h5.zip" from wasabi gives an error. 

<img width="1096" alt="Screenshot 2024-01-26 at 1 12 57 AM" src="https://github.com/cositools/cosipy/assets/111451184/42ccbaef-c91c-4cc3-9231-21a17f5d2e33">

The actual download results in this xml file.

**Comment by parshadkp** [comment]
Hi @ckarwin, sorry that is just a typo in my post. I get that error from downloading through wasabi's website. 

I also tried the command (which gives me the error below): 
(COSI) parshadkp@Parshads-MacBook-Pro cosi-data-challenge-2 % AWS_ACCESS_KEY_ID=GBAL6XATQZNRV3GFH9Y4 AWS_SECRET_ACCESS_KEY=GToOczY5hGX3sketNO2fUwiq4DJoewzIgvTCHoOv aws s3api get-object  --bucket cosi-pipeline-public --key cosi-pipeline-public/COSI-SMEX/DC2/Responses/SMEXv12.Continuum.HEALPixO3_10bins_log_flat.binnedimaging.imagingresponse.nonsparse_nside8.area.good_chunks_unzip.h5.zip --endpoint-url=https://s3.us-west-1.wasabisys.com SMEXv12.Continuum.HEALPixO3_10bins_log_flat.binnedimaging.imagingresponse.nonsparse_nside8.area.good_chunks_unzip.h5.zip

An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

**Comment by ckarwin** [comment]
The `--key` should not include `cosi-pipeline-public/`. That is specified in the `--bucket`. So the command is: 

AWS_ACCESS_KEY_ID=GBAL6XATQZNRV3GFH9Y4 AWS_SECRET_ACCESS_KEY=GToOczY5hGX3sketNO2fUwiq4DJoewzIgvTCHoOv aws s3api get-object --bucket cosi-pipeline-public --key COSI-SMEX/DC2/Responses/SMEXv12.Continuum.HEALPixO3_10bins_log_flat.binnedimaging.imagingresponse.nonsparse_nside8.area.good_chunks_unzip.h5.zip --endpoint-url=https://s3.us-west-1.wasabisys.com SMEXv12.Continuum.HEALPixO3_10bins_log_flat.binnedimaging.imagingresponse.nonsparse_nside8.area.good_chunks_unzip.h5.zip

I just tested it, and it works for me. Please try and let me know if it works.

**Comment by parshadkp** [comment]
Ah, it works. Thank you so much!

Is it not possible to download from the wasabi website though? It results in the .xml file when I try to.

**Comment by ckarwin** [comment]
It should also be possible to download from the website, although I have gotten a similar error at times in the past. I'm not really sure why this happens. Usually the issue can be resolved by logging out and then logging in again. If that doesn't work, then try downloading the file again at a later time (e.g. maybe in an hour or two). Please let me know if the you are eventually able to download the file or if the issue persist.

**Comment by parshadkp** [comment]
Tried logging in and out. Still the same .xml file that is downloaded. It only happens with the zip files. I'm only a Mac M1 if that helps at all.

**Comment by ckarwin** [comment]
Hi @parshadkp Thank you for the feedback. To clarify, do the `.gz` files work ok, and the only issue is with the `.zip` files?

**Comment by parshadkp** [comment]
Just tried a .gz file, doesn't work either. Getting the same .xml file when trying to download any files from wasabi's website. The command line works fine though.

**Comment by ckarwin** [comment]
Ok, I'll look into this and get back to you.

**Comment by ckarwin** [comment]
Hi @parshadkp,
I have clarified the download instructions on the DC2 git page. In summary, for users outside of the COSI collaboration, the data can be downloaded using the command line prompt. Developers within the COSI collaboration can also access the data on wasabi, but they will need the appropriate logon credentials. Can you clarify for me: are you in the COSI collaboration? If so, are you able to download the files now from wasabi (using the needed logon info), or is this still an issue?

**Comment by parshadkp** [comment]
Hi @ckarwin, I am on the COSI collaboration but I do not have the login credentials for the Wasabi website.

**Comment by ckarwin** [comment]
@parshadkp Can you send me a direct message on COSI slack and I'll send you the login credentials for Wasabi?

**Comment by ckarwin** [comment]
I sent @parshadkp all the logon info needed for wasabi, and the files can now be downloaded ok. That closes this issue.
