### ISSUE TITLE
GRB localization - unable to open file

### ISSUE THREAD

**Issue by StevenBoggs** [cositools/cosipy#136]
I'm trying out the GRB localization notebook. (Beautifully done notebook BTW!) Commands [1]-[6] seemed to work OK -- there was no indication of successful execution, just no errors. On command [7] I get this missing file error, it looks like it is looking for the developer's directory? 

![Screenshot 2024-02-15 at 1 37 09 PM](https://github.com/cositools/cosipy/assets/160159429/70a63ad3-afbf-4b3c-a88f-34c2213c424d)

**Comment by Yong2Sheng** [comment]
Hi Steven, 

Thank you for trying it out! Could you please try to replace the response path to see if it can solve the issue? It's the 5th cell of the notebook:
<img width="987" alt="image" src="https://github.com/cositools/cosipy/assets/64873064/96e6ac0f-a7ec-48ef-8d64-2d2430482076">

Thanks!

**Comment by StevenBoggs** [comment]
Hahaha, thanks @Yong2Sheng , amateur error on my part. Still having some troubles on this workbook but I will document them and submit.

**Comment by israelmcmc** [comment]
Thanks, @StevenBoggs and @Yong2Sheng . @Yong2Sheng: can you please move all the paths the user needs to replace to variables in a single cell near the top? I think that would make it less error prone.

**Comment by ckarwin** [comment]
I copy below a comment from @StevenBoggs. In general, this will be a good format to follow for all the notebooks: 

> Two minor comments on that. First, I really like how the spectral notebook has each of the file downloads in a separate cell so they can be run individually as needed. Second, it would be a nice touch to add the file size next to each listed file to download just to give some idea how large these will be while we are waiting for each to download.

**Comment by israelmcmc** [comment]
#150 closes this issue.
