### ISSUE TITLE
Data I/O notebook: Pandas Deprecation Warning

### ISSUE THREAD

**Issue by avalluvan** [cositools/cosipy#138]
In the `DataIO_example.ipynb` notebook, `pd.read_csv` function, a specific keyword `delim_whitespace` is deprecated in the latest version of pandas v2.2.0. The warning recommends to use the keyword `sep` instead. There are about 6 instances of the former keyword in the notebook (and this warning may also affect other scenarios where a .dat, .txt or .csv file is being read)
![Screenshot 2024-02-13 223053](https://github.com/cositools/cosipy/assets/62253557/611f6deb-d288-4bbc-8fc5-bee207448a77)

**Comment by avalluvan** [comment]
@code authors, do you think it will help if there is a single issue containing all posts related to warnings (not errors)? Or would you prefer separate issues?

**Comment by ckarwin** [comment]
Thanks @avalluvan. I will get this updated. I think it's probably best to open separate issues for deprecation warnings.

**Comment by ckarwin** [comment]
I think this issue has been resolved for the dataIO class. Please open a new issue if this happens somewhere else. Thanks.
