### ISSUE TITLE
Root call in Crab Imaging notebook

### ISSUE THREAD

**Issue by StevenBoggs** [cositools/cosipy#139]
Got through all 3 Crab imaging workbooks fine until near the very end of Crab-DC2-ScAtt-Upsampling:

<img width="1207" alt="Screenshot 2024-02-19 at 7 07 49 PM" src="https://github.com/cositools/cosipy/assets/160159429/ecbeaea3-be6d-4dcf-b318-eac868ffce25">

First I've seen this error, is Root expected for running these notebooks in DC2?

**Comment by ckarwin** [comment]
Hi @hirokiyoneda, I think this is resolved now. Can we close this issue?
