### ISSUE TITLE
Reorganize Point_source_resonse.ipynb (to be called SpacecraftFile.ipynb) and DetectorResponse.ipynb tutorials.

### ISSUE THREAD

**Issue by israelmcmc** [cositools/cosipy#147]
Following up from PR #145 

- What is currently called "Point_source_resonse.ipynb" will change names to "SpacecraftFile.ipynb" and focus on the coordinates, orientation, etc. (described in 2. above)
- I'll add the explanation of the scatt map to SpacecraftFile.ipynb
- @Yong2Sheng will move the actual point source calculation to “DetectorResponse.ipynb” (that is, replacing my code with a fake orientation history)
- PR #145  must be merged first

**Comment by ckarwin** [comment]
PR #145 has been merged.
