### ISSUE TITLE
Utilities methods not rendering in docs

### ISSUE THREAD

**Issue by ckarwin** [cositools/cosipy#148]
docs: https://cositools.github.io/cosipy/api/util.html

This might be due to the imports being used: `awscli.clidriver`

Although, I see that awscli is already included in https://github.com/cositools/cosipy/blob/main/docs/conf.py

**Comment by ckarwin** [comment]
The TS map and DataIO methods are also not rendering.

**Comment by avalluvan** [comment]
I am facing the same issue. Is there a temporary fix?

**Comment by ckarwin** [comment]
This should be fixe once PR #156 is merges, which should be soon.
