### ISSUE TITLE
No doc strings in cosipy.ts_map.TSMap

### ISSUE THREAD

**Issue by ckarwin** [cositools/cosipy#152]
None of the methods in cosipy.ts_map.TSMap have doc strings.

**Comment by Yong2Sheng** [comment]
Hi @ckarwin,

I add the doc string for [TSMap.py](https://github.com/Yong2Sheng/cosipy_SpacecraftFile/blob/fast_ts_map_galactic/cosipy/ts_map/TSMap.py) and updated the doc string for [SpacecraftFile.py](https://github.com/Yong2Sheng/cosipy_SpacecraftFile/blob/fast_ts_map_galactic/cosipy/spacecraftfile/SpacecraftFile.py), [scatt_map.py](https://github.com/Yong2Sheng/cosipy_SpacecraftFile/blob/fast_ts_map_galactic/cosipy/spacecraftfile/scatt_map.py), [fast_ts_fit.py](https://github.com/Yong2Sheng/cosipy_SpacecraftFile/blob/fast_ts_map_galactic/cosipy/ts_map/fast_ts_fit.py) for better format in #150

**Comment by ckarwin** [comment]
Thanks, @Yong2Sheng. I linked this issue to your PR #150, so that it should be closed when your PR is merged.

**Comment by israelmcmc** [comment]
#150 closed this.
