### ISSUE TITLE
New dependency: psutil

### ISSUE THREAD

**Issue by israelmcmc** [cositools/cosipy#155]
I recent PR added a psutil as a new depency: https://github.com/cositools/cosipy/pull/145

This broke the docs build since psutil needs to be added to the mocked packages.

I haven't checked if it broke the installation, since maybe psutil was already a secondary dependency.

**Comment by israelmcmc** [comment]
It does seem to be installed by other dependencies, including 3ML. the issue is then only the docs

**Comment by ckarwin** [comment]
Ok, makes sense. Thanks for figuring this out!
