### ISSUE TITLE
Wrong background file name in the TS map notebook

### ISSUE THREAD

**Issue by NicoloParmiggiani** [cositools/cosipy#161]
In this notebook https://github.com/cositools/cosipy/blob/main/docs/tutorials/ts_map/Parallel_TS_map_computation_DC2.ipynb

the background file name is different in different parts of the code.

Is is downloaded as "bkg_binned_data_local.hdf5" and then used as "bkg_binned_data_1s_local.hdf5".

**Comment by israelmcmc** [comment]
Thanks @NicoloParmiggiani. @Yong2Sheng can you look into this, please?

**Comment by Yong2Sheng** [comment]
This is a file name issue. This will be fixed once #150 is merged. Thanks!

**Comment by israelmcmc** [comment]
#150 closed this.
