### ISSUE TITLE
pip install cosipy issue with astromodels

### ISSUE THREAD

**Issue by nmik** [cositools/cosipy#165]
I was having an issue with installing cosipy with pip that was crushing when building the astromodels:

<img width="645" alt="Screenshot 2024-03-18 at 2 33 59 AM" src="https://github.com/cositools/cosipy/assets/19571835/85cdd19b-3a71-46b7-b5b0-22cf7712fe19">

The prompt error also suggested the following:

<img width="636" alt="Screenshot 2024-03-18 at 2 34 37 AM" src="https://github.com/cositools/cosipy/assets/19571835/86abb7e7-93ea-4b93-af14-7feb2aa8ddd0">

Which worked:

`pip install  --use-pep517 -e .`

I haven't tried if the non developer version of the pip installation also works:

`pip install cosipy==0.0.2a --use-pep517`

**Comment by israelmcmc** [comment]
@nmik can you try with Python 3.10, please? 

I remember seeing this before, I think it's related to issue #127 (which is really an issue with one of our dependencies)

**Comment by nmik** [comment]
@israelmcmc I dis start from scratch from a new conda environment following the instructions here: [https://cositools.github.io/cosipy/install.html ](https://cositools.github.io/cosipy/install.html )

I created the conda environment with:
`conda create -n <cosipy_env_name> python=3.10 pip`

Indeed the python version in the environment is 
`Python 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:59) [Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.`

**Comment by israelmcmc** [comment]
Python 3.10 worked. Closing this issue.
