### ISSUE TITLE
h5py pip installation issue

### ISSUE THREAD

**Issue by israelmcmc** [cositools/cosipy#174]
Hi @israelmcmc. Following your advice I tried unsetting HEADAS and I believe that worked. 

However, I then had another installation issue since I was missing hdf5 library.
Specifically, I had to install the library via conda (i.e., `conda install h5py`) and the installation looks to have completed fine. 
Installing via pip (i.e., `pip install h5py`) didn't  work, but I think it would have worked if I also properly set HDF5_DIR environment variable to point to where the hdf5 header file would be. I'm not sure if it is mentioned anywhere that hdf5 is required for cosipy (or maybe everyone has it and I just didn't for some reason). 

(Also, sorry if this is the wrong thread to attach this to!) 

_Originally posted by @mikemoss3 in https://github.com/cositools/cosipy/issues/173#issuecomment-2045399011_

**Comment by israelmcmc** [comment]
@mikemoss3 Can you share the error message that you are seeing, please? h5py is automatically installed with cosipy (as a derived requirement of histpy). However, that's all through pip, which you mentioned didn't work for you.

**Comment by mikemoss3** [comment]
@israelmcmc luckily, I saved this error message as well! (see attached file) 
[install-error-hdf5.txt](https://github.com/cositools/cosipy/files/14923996/install-error-hdf5.txt)

Let me know if I can provide any further information.

**Comment by israelmcmc** [comment]
Thanks @mikemoss3! One last thing, please. Which system are you using? And if macos, do you have an M1 chip?

**Comment by mikemoss3** [comment]
Yes, I am on MacOS and it's the Apple M1 Pro chip.

**Comment by Yong2Sheng** [comment]
I have the same issue with the M1 Mac.

**Comment by israelmcmc** [comment]
I think this is related to these issue(s) in h5py:
https://github.com/h5py/h5py/issues/1810
https://github.com/h5py/h5py/issues/1800

It seems that at the moment there's no good solution other than asking the M1 users to install HDF5 either through homebrew or conda. 

I added this info to the installation instructions. I'm closing this issue since once the h5py developer fix this, it will automatically propagate to the cosipy installation.
