### ISSUE TITLE
Test Crab DC fit with Earth Occulted workaround

### ISSUE THREAD

**Issue by israelmcmc** [cositools/cosipy#179]
@Yong2Sheng showed that issue with the Crab expected counts is that the response did not account for Earth occultations (but the simulation did).

We need to fully close the loop on this by fitting the Crab and making sure the resulting spectrum matches the input. Basically re-running the Crab Spectral fit tutorial with a new response.

**Comment by israelmcmc** [comment]
Code to fudged Earth occultation on the response (it only works for DC2 because the SC was always pointed at zenith)
```
from cosipy.response import FullDetectorResponse

import numpy as np
from pathlib import Path
import h5py as h5

data_dir = Path("/Users/imartin5/cosi/data_challenge/cosi-data-challenge-2/data") # Current directory by default. Modify if you can want a different path

response_path = data_dir/"SMEXv12.Continuum.HEALPixO3_10bins_log_flat.binnedimaging.imagingresponse.nonsparse_nside8.area.good_chunks_unzip.h5"

response_path_new = data_dir/"SMEXv12.Continuum.HEALPixO3_10bins_log_flat.binnedimaging.imagingresponse.nonsparse_nside8.area.good_chunks_unzip.earthocc.h5"

response = FullDetectorResponse.open(response_path)

nulambda_axis = response.axes['NuLambda']
theta,phi = nulambda_axis.pix2ang(range(nulambda_axis.npix))

with h5.File(response_path_new, 'r+') as response_file:

    for pix in np.where(theta > np.deg2rad(113))[0]:

        response_file['DRM']['CONTENTS'][pix] = 0    
```

**Comment by israelmcmc** [comment]
@ckarwin @Yong2Sheng My understanding is that while the Earth occultation does help, there are still substantial discrepancies. Most likely due to how coarse the response is. Can you both please summarize your findings here (or simply attach your slides) and then we can close this issue.

**Comment by Yong2Sheng** [comment]
Hi @israelmcmc,

The thing I don't understand is how the coarseness affects the injected counts.

My original understanding is that although the response is coarse, the fitting procedure should be able to find a good solution that matches the simulated counts by varying the parameters of the band function. 

Note that the good solution is not the true solution.

I do understand it's possible that the allowed guess range of the fitting doesn't include a good solution or the coarseness results in a solution that won't be able to be good, no matter how we adjust the parameters of the band function.

Could you please comment on this? Thank you!

**Comment by israelmcmc** [comment]
Hi @Yong2Sheng 

There's the binning of the axes with measured quantities (e.g. $E_m$) and those for physical input values (e.g. $E_i$). The binning of $E_m$ and other measured ones can indeed be coarse and it wouldn't matter, you would lose some sensitivity but you would get the right answer. The problem is how coarse the $E_i$ and other physical axes are because you lose some information fue to a discretization effect. For example, you generate the response with a spectrum $F_1$, but later try to simulate a spectrum $F_2$. Ideally, you would need to weight each simulated event by a factor $\sim F_1(E_i)/F_2(E_i)$, but instead you end up with a weight for every bin  $\sim \int F_1(E_i) dE_i / \int F_2(E_i) dE_i$ which inevitably has some error, which however can become negligible if the bin size is small.

  And then:
  > I do understand it's possible that the allowed guess range of the fitting doesn't include a good solution or the coarseness results in a solution that won't be able to be good, no matter how we adjust the parameters of the band function.

This is indeed what happens. Since your response is coarse, it can't accurately represent $F_2$, and none of the combinations of the parameter space match the counts perfectly. You have fewer parameters than the number of bins, so a perfect match is not guaranteed.

**Comment by Yong2Sheng** [comment]
After discussion with @israelmcmc, I think everything makes senses now. Closing this issue.

**Comment by Yong2Sheng** [comment]
Hi @israelmcmc, it seems that I don't have the permission to edit or close this issue. Could you please close this issue or give me permission to do that? Thank you!

**Comment by israelmcmc** [comment]
Thanks @Yong2Sheng. I'll close it.
