### ISSUE TITLE
Issue with matplotlib version 3.9.0 (released May 15)

### ISSUE THREAD

**Issue by avalluvan** [cositools/cosipy#180]
Matplotlib seems to have moved around some functions such as `get_cmap()` in `matplotlib.cm`. The out-of-the-box installation should impose a constraint on the matplotlib version to 3.8.3 or earlier.

**Comment by ckarwin** [comment]
This seems to be the same error that is causing the automatic unit tests to fail for #175:  module 'matplotlib.cm' has no attribute 'get_cmap'

**Comment by ckarwin** [comment]
Thanks @avalluvan We restricted the matplotlib version to be <= 3.8.3 in PR #175 and it fixed the issue with the automatic checks. I think we can close this for now. Please open the issue again if the problem remains.
