### ISSUE TITLE
Move the `get_psr_in_galactic` to class `AllSkyPointSourceResponse`

### ISSUE THREAD

**Issue by Yong2Sheng** [cositools/cosipy#229]
I  can put the function [`get_psr_in_galactic`](https://github.com/Yong2Sheng/cosipy_SpacecraftFile/blob/f77143da464636947fdceac8f93eda5eb7aa8e87/cosipy/ts_map/fast_ts_fit.py#L146) in an util.py file in response for mow to avoid the code duplication. (Will do this later in a PR).

This issue is a reminder to move `get_psr_in_galactic` to a new class called `AllSkyPointSourceResponse`.

**Comment by israelmcmc** [comment]
Can be done together with #129

**Comment by israelmcmc** [comment]
Closing and merging with #129.
