### ISSUE TITLE
Small bug in attitude.py for x pointing calculation

### ISSUE THREAD

**Issue by ckierans** [cositools/cosipy#23]
Got error the following error:
    159     raise ValueError("At least two axes are needed.")
    161 if x is None:
--> 162     x = y.cross(x)
    163 elif y is None:
    164     y = z.cross(x)

Line 162 of attitude.py should be x = y.cross(z)

**Comment by israelmcmc** [comment]
Thanks @ckierans.

I fixed this in scoords https://github.com/cositools/scoords/commit/42eefe58907af4f7382e0b9a0f992926a91a0242. 
This issue should be closed when #24 is closed.

**Comment by israelmcmc** [comment]
#24 closed.
