### ISSUE TITLE
Check that simulated data only has Compton events

### ISSUE THREAD

**Issue by ckarwin** [cositools/cosipy#236]
The `read_tra` method in the `dataIO` class can only handle Compton events. If the simulated data includes single site events, it will throw an error which is difficult to trace back. We should add a test for this that will throw a clear error message if trying to read a tra file that contains single site events. 

Note: Eventually we should add another method to parse tra files with single site events.

**Comment by GallegoSav** [comment]
I created  a pull request . If there is a event which is not compton in the tra file, it will raise an error

**Comment by ckarwin** [comment]
Issue has been fixed with PR #253.
