### ISSUE TITLE
Can't read the old spacecraft file

### ISSUE THREAD

**Issue by Yong2Sheng** [cositools/cosipy#260]
The pull request #258 seems breaking the reading of the old spacecraft file `20280301_3_month.ori`, which has no columns for altitude and Earth zenith.

This is caused by changing
```
orientation_file = np.loadtxt(file, usecols=(1, 2, 3, 4, 5), delimiter=' ', skiprows=1, comments=("#", "EN"))
```
to
```
orientation_file = np.loadtxt(file, usecols=(1, 2, 3, 4, 5, 6, 7, 8),delimiter=' ', skiprows=1, comments=("#", "EN"))
```
@ckarwin @GallegoSav @israelmcmc Maybe we should modify the old spacecraft file `20280301_3_month.ori` by adding null columns or let the code to decide the number of columns to read.

**Comment by israelmcmc** [comment]
Indeed, I don't want to get slowed down or make the code too clunky at this point by trying to make everything backward compatible, it's still too early. We'll have to update the notebooks to use the new ori file though.
