### ISSUE TITLE
need to export the python path of cosipy in your bashrc file

### ISSUE THREAD

**Issue by GallegoSav** [cositools/cosipy#34]
If you install only cosipy from scratch (and not cositool) you need to add this line on your `bashrc` file : 
`export PYTHONPATH=$PYTHONPATH:/your/path/tocosipy/folder`

Otherwise you will get errors when trying to import cosipy functions

**Comment by israelmcmc** [comment]
I think it is working in DC2. @GallegoSav if it doesn't work for you, please feel free to reopen this.
