### ISSUE TITLE
Remove hardcoded unbinned data output.

### ISSUE THREAD

**Issue by israelmcmc** [cositools/cosipy#49]
https://github.com/cositools/cosipy/blob/fa5259c0906f8e8217df7df640d54c1a82ef5d09/cosipy/data_io/UnBinnedData.py#L288

Add it to yaml file.

**Comment by ckarwin** [comment]
@israelmcmc Do you prefer to not write the unbinned data to file by default?

**Comment by israelmcmc** [comment]
Yeah 😁 . See my long response here https://github.com/cositools/cosipy/issues/63#issuecomment-1743609958
