### ISSUE TITLE
cannot import cosipy

### ISSUE THREAD

**Issue by ckarwin** [cositools/cosipy#80]
I just updated to the most recent version of cosipy and I can't  run import cosipy. This issue is caused by an import in COSILike.py: 

from cosipy.coordinates.orientation import Orientation_file

If I comment this file out I can import cosipy.

Also, I am not sure who is working on the coordinates class, but the corresponding __init__ files have not been set up.

**Comment by eneights** [comment]
The Orientation_file import is fixed in my pull request.

**Comment by ckarwin** [comment]
Thanks, Eliza. I'll take a look at your PR.

**Comment by ckarwin** [comment]
@eneights, I see @israelmcmc has already been going through your PR. I will wait for those comments to resolve.
