### ISSUE TITLE
Add an option in which intermediate files are not saved automatically

### ISSUE THREAD

**Issue by hiyoneda** [cositools/cosipy#85]
Related to #63, it is better to add an option in which intermediate files are not saved automatically in the orientation module. The suggestions are:

- In the method “get_target_in_sc_frame”, with “quiet == True”, line 302 can be off (np.save ….)
- In the method “get_dwell_map”, please make an option to turn off Line 357 (self.dwell_map.write_map …)

Then, we can avoid lots of files being saved in the image analysis automatically.

**Comment by israelmcmc** [comment]
Done for DC2
