### ISSUE TITLE
An error when start is the same as the initial value of the registered time array, running SpacecraftFile/source_interval

### ISSUE THREAD

**Issue by hiyoneda** [cositools/cosipy#87]
When running `ori_filetered = ori.source_interval(ori.get_time()[0], ori.get_time()[5000])`,  I got an error `ValueError: array of sample points is empty`
It seems because `start_idx = self._load_time.searchsorted(start.value) - 1` gives -1 in such a case.

**Comment by israelmcmc** [comment]
@hiyoneda @saurabhmittal23 @Yong2Sheng What's the status on this one?

**Comment by Yong2Sheng** [comment]
Hi @israelmcmc, I tested `ori_filetered = ori.source_interval(ori.get_time()[0], ori.get_time()[5000])` using the 3-month orientation file of DC2, and there is no error now. So it has been fixed.

**Comment by israelmcmc** [comment]
Thanks! I'm closing it then
