### ISSUE TITLE
Error when converting tra to .h5

### ISSUE THREAD

**Issue by Yong2Sheng** [cositools/cosipy#90]
The simulated tra file is attached. 

The issue comes from the tra file with extra headers:

> Type      tra
> Version   1
> Geometry  /home/sheng2/astrohe_yong/COSI/MassModel/ComptonSphere/ComptonSphere.geo.setup
> 
> Date      2023-10-18 22:10:48
> MEGAlib   3.99.01
> 
> SE
> ET CO
> ID 1
> TI 0.001442000
> GX 0 -90
> GZ 180 0
> SQ 3
> CT 0.0380275 0.149116
> TL 1
> TE 254.705
> CE 182.004 0.639403   254.705 0.509696

[GRB100100010_3.inc1.id1.tra.gz](https://github.com/cositools/cosipy/files/13036178/GRB100100010_3.inc1.id1.tra.gz)

**Comment by ckarwin** [comment]
Hi Yong, Can you be a bit more specific. What are you running and what is the error?

**Comment by Yong2Sheng** [comment]
Hi Chris, here is the error I got (see the attachment)
![Xnip2023-10-18_22-41-35](https://github.com/cositools/cosipy/assets/64873064/ef1b0bf8-8df6-47fb-b6ef-cda858f920ae)

I thinks it might be caused by the lines at the start of the tra file.

**Comment by ckarwin** [comment]
Ok, thanks. It looks like I just need to account for the possibility of empty lines. I'm about to make a PR with a number of updates to the DataIO. I'll make sure this is fixed.

**Comment by Yong2Sheng** [comment]
Thanks Chris!

**Comment by Yong2Sheng** [comment]
I have one more question here: are tmin and tmax necessary parameters in `inputs.yaml`? 

For example, I simulated a random GRB for 2s without orientation. I just need to extract and convert the whole dataset to a .h5 file. But in this case I don't know the tmin and tmax unless I load and check the tra file mimrec, which requires extra steps using MEGAlib.

**Comment by ckarwin** [comment]
Ok I think I fixed it. For now, can you try the following in your branch to see if it works for you:
line 143 in https://github.com/cositools/cosipy/blob/main/cosipy/data_io/UnBinnedData.py
add the following:
if len(this_line) == 0:
     continue

**Comment by ckarwin** [comment]
make sure continue is indented.

**Comment by ckarwin** [comment]
For now you need to specify all the parameters in the inputs.yaml file. If you don't use them then just put in arbitrary values. This is another thing I need to fix, and I'll be doing it soon.

**Comment by Yong2Sheng** [comment]
Thanks! The reading issue caused by the empty line is fixed now!

**Comment by ckarwin** [comment]
Great. It will be included in the next dataIO PR. I will keep this issue open until then.
