### ISSUE TITLE
Add option to read tra file with no associated pointing information

### ISSUE THREAD

**Issue by ckarwin** [cositools/cosipy#95]
short description:
Need to add option in dataIO to read tra file with no pointing information. 

long description:
The read_tra() method requires some associated pointing information (either directly in the tra file or via an ori file). This is needed to convert the data from local coordinates to Galactic. However, sometimes simulations are ran just in local coordinates, with no pointing information. In this case, the data cannot be converted to Galactic coordinates. An option needs to be added to allow for this.

**Comment by israelmcmc** [comment]
@ckarwin What's the status on this one? Or maybe it's not needed anymore?

**Comment by ckarwin** [comment]
@israelmcmc I think it's still needed. I'll get this implemented soon.

**Comment by israelmcmc** [comment]
Thanks. Yeah, that's alright, just trying to keep the list of issues up to date
